project: 
  type: website
  output-dir: docs
execute: 
  freeze: auto
format:
  html:
    embed-resources: true
    theme:
      light: litera
      dark: solar
    fontsize: 1em
    linestretch: 1.5
    highlight-style: gruvbox
    df-print: paged